package insmith

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"io"
	"strings"
	"text/template"
)

type config struct {
	repository      string
	binary          string
	workflow        string
	assetPattern    string
	checksumPattern string
	verification    string
}

func runGenerate(args []string, stdout, stderr io.Writer) error {
	flags := flag.NewFlagSet("insmith generate", flag.ContinueOnError)
	flags.SetOutput(stderr)
	binary := flags.String("binary", "", "binary name (defaults to repository name)")
	workflow := flags.String("workflow", "release-build.yaml", "release workflow path for attestation verification")
	assetPattern := flags.String("asset-pattern", "", "asset name pattern using {binary}, {version}, {os}, and {arch}")
	checksumPattern := flags.String("checksum-pattern", "SHA256SUMS", "checksum asset name pattern")
	verification := flags.String("verification", "attestation-or-checksum", "verification policy: attestation, attestation-or-checksum, checksum, or none")
	if err := flags.Parse(args); err != nil {
		if errors.Is(err, flag.ErrHelp) {
			return nil
		}
		return err
	}
	if flags.NArg() != 1 {
		flags.Usage()
		return errors.New("exactly one OWNER/REPO argument is required")
	}

	script, err := generate(config{
		repository:      flags.Arg(0),
		binary:          *binary,
		workflow:        *workflow,
		assetPattern:    *assetPattern,
		checksumPattern: *checksumPattern,
		verification:    *verification,
	})
	if err != nil {
		return err
	}
	_, err = io.WriteString(stdout, script)
	return err
}

func generate(c config) (string, error) {
	parts := strings.Split(c.repository, "/")
	if len(parts) != 2 || !safeFilename(parts[0]) || !safeFilename(parts[1]) ||
		parts[0] == "." || parts[0] == ".." || parts[1] == "." || parts[1] == ".." {
		return "", fmt.Errorf("repository must be in OWNER/REPO form")
	}
	if c.binary == "" {
		c.binary = parts[1]
	}
	if !safeFilename(c.binary) || c.binary == "." || c.binary == ".." {
		return "", fmt.Errorf("binary must contain only letters, digits, dots, underscores, and hyphens")
	}
	if c.assetPattern == "" {
		c.assetPattern = "{binary}_{version}_{os}_{arch}"
	}
	if !safePattern(c.assetPattern) {
		return "", fmt.Errorf("asset pattern contains unsupported characters")
	}
	if c.checksumPattern != "" && !safePattern(c.checksumPattern) {
		return "", fmt.Errorf("checksum pattern contains unsupported characters")
	}
	if c.workflow != "" && !strings.Contains(c.workflow, "/.github/workflows/") {
		c.workflow = strings.TrimPrefix(c.workflow, "/")
		if !strings.HasPrefix(c.workflow, ".github/workflows/") {
			c.workflow = ".github/workflows/" + c.workflow
		}
		c.workflow = c.repository + "/" + c.workflow
	}
	switch c.verification {
	case "attestation", "attestation-or-checksum", "checksum", "none":
	default:
		return "", fmt.Errorf("unknown verification policy %q", c.verification)
	}
	if c.checksumPattern == "" && c.verification != "none" && c.verification != "attestation" {
		return "", fmt.Errorf("checksum pattern must not be empty when checksum verification is enabled")
	}

	var output bytes.Buffer
	if err := scriptTemplate.Execute(&output, struct {
		Repository      string
		Binary          string
		Workflow        string
		AssetPattern    string
		ChecksumPattern string
		Verification    string
	}{
		shellQuote(c.repository),
		shellQuote(c.binary),
		shellQuote(c.workflow),
		shellQuote(c.assetPattern),
		shellQuote(c.checksumPattern),
		shellQuote(c.verification),
	}); err != nil {
		return "", err
	}
	return output.String(), nil
}

func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "'\"'\"'") + "'"
}

func safeFilename(name string) bool {
	return safeName(name, false)
}

func safePattern(name string) bool {
	return safeName(name, true)
}

func safeName(name string, patterns bool) bool {
	if name == "" {
		return false
	}
	for _, r := range name {
		if !(r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' || r == '.' || r == '_' || r == '-' || patterns && (r == '{' || r == '}')) {
			return false
		}
	}
	return true
}

var scriptTemplate = template.Must(template.New("install.sh").Parse(`#!/bin/sh
# Code generated by insmith. DO NOT EDIT.
set -eu

REPOSITORY={{.Repository}}
BINARY={{.Binary}}
WORKFLOW={{.Workflow}}
ASSET_PATTERN={{.AssetPattern}}
CHECKSUM_PATTERN={{.ChecksumPattern}}
VERIFICATION={{.Verification}}
INSTALL_DIR=${INSTALL_DIR:-/usr/local/bin}

fail() {
	printf '%s\n' "insmith: $*" >&2
	exit 1
}

need() {
	command -v "$1" >/dev/null 2>&1 || fail "required command not found: $1"
}

validate_tag() {
	case "$1" in *[!A-Za-z0-9._+-]*) return 1 ;; esac
}

need curl
version=${1:-}
if [ -z "$version" ]; then
	version=$(curl --proto '=https' --proto-redir '=https' --tlsv1.2 -fsSL "https://api.github.com/repos/$REPOSITORY/releases/latest" |
		sed -n 's/^[[:space:]]*"tag_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -n 1)
	[ -n "$version" ] || fail "could not determine the latest release"
fi
validate_tag "$version" || fail "unsupported version: $version"
tag=$version

case $(uname -s) in
	Linux) os=linux ;;
	Darwin) os=darwin ;;
	*) fail "unsupported operating system: $(uname -s)" ;;
esac
case $(uname -m) in
	x86_64|amd64) arch=amd64 ;;
	aarch64|arm64) arch=arm64 ;;
	*) fail "unsupported architecture: $(uname -m)" ;;
esac

asset_base=$(printf '%s' "$ASSET_PATTERN" |
	sed -e "s/{binary}/$BINARY/g" -e "s/{version}/$tag/g" -e "s/{os}/$os/g" -e "s/{arch}/$arch/g")
release_api="https://api.github.com/repos/$REPOSITORY/releases/tags/$tag"
release_json=$(curl --proto '=https' --proto-redir '=https' --tlsv1.2 -fsSL "$release_api") || fail "could not find release $version"
asset_urls=$(printf '%s\n' "$release_json" |
	sed -n 's/^[[:space:]]*"browser_download_url"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')

asset_url_for_name() {
	wanted=$1
	while IFS= read -r url; do
		[ "${url##*/}" = "$wanted" ] && printf '%s\n' "$url"
	done <<-EOF
	$asset_urls
	EOF
	return 0
}

matches=
for extension in .tar.gz .zip ''; do
	candidate=$asset_base$extension
	found=$(asset_url_for_name "$candidate")
	[ -z "$found" ] || matches="${matches}${matches:+
}$found"
done
[ -n "$matches" ] || fail "could not find an asset matching $asset_base (.tar.gz, .zip, or raw binary)"
[ "$(printf '%s\n' "$matches" | wc -l | tr -d ' ')" -eq 1 ] ||
	fail "asset selection is ambiguous for $asset_base"
asset_url=$matches
asset_name=${asset_url##*/}

tmpdir=$(mktemp -d "${TMPDIR:-/tmp}/insmith.XXXXXX") || fail "could not create temporary directory"
trap 'rm -rf "$tmpdir"' 0
trap 'exit 1' HUP INT TERM
artifact="$tmpdir/$asset_name"
curl --proto '=https' --proto-redir '=https' --tlsv1.2 -fsSL "$asset_url" -o "$artifact" || fail "could not download $asset_name"

verify_checksum() {
	checksum_name=$(printf '%s' "$CHECKSUM_PATTERN" |
		sed -e "s/{version}/$tag/g" -e "s/{binary}/$BINARY/g")
	checksum_url=$(asset_url_for_name "$checksum_name")
	[ "$(printf '%s\n' "$checksum_url" | sed '/^$/d' | wc -l | tr -d ' ')" -eq 1 ] ||
		fail "could not find a unique checksum asset named $checksum_name"
	checksums="$tmpdir/$checksum_name"
	curl --proto '=https' --proto-redir '=https' --tlsv1.2 -fsSL "$checksum_url" -o "$checksums" || fail "could not download checksums"
	expected=$(awk -v name="$asset_name" '$2 == name || $2 == "*" name { print $1; exit }' "$checksums")
	[ -n "$expected" ] || fail "checksum for $asset_name is missing"
	if command -v sha256sum >/dev/null 2>&1; then
		actual=$(sha256sum "$artifact" | awk '{print $1}')
	elif command -v shasum >/dev/null 2>&1; then
		actual=$(shasum -a 256 "$artifact" | awk '{print $1}')
	elif command -v openssl >/dev/null 2>&1; then
		actual=$(openssl dgst -sha256 "$artifact" | awk '{print $NF}')
	else
		fail "no SHA-256 command is available"
	fi
	[ "$expected" = "$actual" ] || fail "checksum verification failed for $asset_name"
}

verify_attestation() {
	command -v gh >/dev/null 2>&1 || return 2
	# GitHub CLI 2.93.0 introduced safe --signer-digest attestation verification.
	gh_version=$(gh --version 2>/dev/null | awk 'NR == 1 { sub(/^gh version /, "", $0); split($0, v, "."); sub(/[^0-9].*/, "", v[3]); print v[1] * 1000000 + v[2] * 1000 + v[3] }')
	[ -n "$gh_version" ] && [ "$gh_version" -ge 2093000 ] || return 2
	gh attestation verify --help >/dev/null 2>&1 || return 2
	gh attestation verify --help 2>&1 | grep -q -- '--signer-digest' || return 2
	command -v git >/dev/null 2>&1 || return 2
	commit=$(git ls-remote "https://github.com/$REPOSITORY.git" "refs/tags/$tag^{}" | awk 'NR == 1 { print $1 }')
	if [ -z "$commit" ]; then
		commit=$(git ls-remote "https://github.com/$REPOSITORY.git" "refs/tags/$tag" | awk 'NR == 1 { print $1 }')
	fi
	[ -n "$commit" ] || return 2
	if [ -n "$WORKFLOW" ]; then
		gh attestation verify "$artifact" --repo "$REPOSITORY" --source-digest "$commit" --signer-digest "$commit" --signer-workflow "$WORKFLOW" || return 1
	else
		gh attestation verify "$artifact" --repo "$REPOSITORY" --source-digest "$commit" --signer-digest "$commit" || return 1
	fi
}

case "$VERIFICATION" in
	none) ;;
	checksum) verify_checksum ;;
	attestation)
		if verify_attestation; then
			:
		else
			status=$?
			if [ "$status" -eq 2 ]; then
				fail "GitHub attestation verification is unavailable"
			else
				fail "attestation verification failed"
			fi
		fi
		;;
	attestation-or-checksum)
		if verify_attestation; then
			:
		else
			status=$?
			if [ "$status" -eq 2 ]; then
				verify_checksum
			else
				fail "attestation verification failed"
			fi
		fi
		;;
esac

check_archive_member() {
	member=$1
	case "$member" in
		/*) fail "archive contains an absolute path: $member" ;;
	esac
	case "/$member/" in
		*/../*) fail "archive contains a path traversal entry: $member" ;;
	esac
}

check_archive_symlinks() {
	while IFS= read -r line; do
		case "$line" in
			l*) fail "archive contains a symlink entry which is not supported" ;;
			h*) fail "archive contains a hard link entry which is not supported" ;;
		esac
	done <<-EOF
	$1
	EOF
}

executable=
extractdir="$tmpdir/extract"
mkdir -p "$extractdir" || fail "could not create extraction directory"
case "$asset_name" in
	*.tar.gz)
		need tar
		tar_listing=$(tar -tvzf "$artifact") || fail "could not list $asset_name contents"
		check_archive_symlinks "$tar_listing"
		tar_names=$(tar -tzf "$artifact") || fail "could not list $asset_name contents"
		while IFS= read -r member; do
			[ -n "$member" ] || continue
			check_archive_member "$member"
		done <<-EOF
		$tar_names
		EOF
		tar -xzf "$artifact" -C "$extractdir"
		;;
	*.zip)
		need unzip
		zip_names=$(unzip -Z1 "$artifact") || fail "could not list $asset_name contents"
		while IFS= read -r member; do
			[ -n "$member" ] || continue
			check_archive_member "$member"
		done <<-EOF
		$zip_names
		EOF
		zip_types=$(unzip -Z -s "$artifact") || fail "could not list $asset_name contents"
		check_archive_symlinks "$zip_types"
		unzip -q "$artifact" -d "$extractdir"
		;;
	*)
		executable=$artifact
		;;
esac
[ -n "$executable" ] || executable=$(find "$extractdir" -type f -name "$BINARY" -print | head -n 1)
[ -n "$executable" ] || fail "could not find executable $BINARY in $asset_name"
mkdir -p "$INSTALL_DIR" || fail "could not create $INSTALL_DIR"
install -m 0755 "$executable" "$INSTALL_DIR/$BINARY" || fail "could not install $BINARY"
printf 'Installed %s to %s\n' "$BINARY" "$INSTALL_DIR/$BINARY"
`))
