package main

import (
	"bytes"
	"fmt"
	"path"
	"strings"
	"text/template"
)

type config struct {
	repository      string
	binary          string
	workflow        string
	assetPattern    string
	checksumPattern string
	verification    string
}

func generate(c config) (string, error) {
	parts := strings.Split(c.repository, "/")
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		return "", fmt.Errorf("repository must be in OWNER/REPO form")
	}
	if c.binary == "" {
		c.binary = parts[1]
	}
	if c.assetPattern == "" {
		c.assetPattern = "{binary}_{version}_{os}_{arch}"
	}
	switch c.verification {
	case "attestation", "attestation-or-checksum", "checksum", "none":
	default:
		return "", fmt.Errorf("unknown verification policy %q", c.verification)
	}
	if c.checksumPattern == "" && c.verification != "none" && c.verification != "attestation" {
		return "", fmt.Errorf("checksum pattern must not be empty when checksum verification is enabled")
	}

	var output bytes.Buffer
	if err := scriptTemplate.Execute(&output, struct {
		Repository      string
		Binary          string
		Workflow        string
		AssetPattern    string
		ChecksumPattern string
		Verification    string
	}{
		shellQuote(c.repository),
		shellQuote(c.binary),
		shellQuote(c.workflow),
		shellQuote(c.assetPattern),
		shellQuote(c.checksumPattern),
		shellQuote(c.verification),
	}); err != nil {
		return "", err
	}
	return output.String(), nil
}

func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "'\"'\"'") + "'"
}

var scriptTemplate = template.Must(template.New("install.sh").Parse(`#!/bin/sh
# Code generated by insmith. DO NOT EDIT.
set -eu

REPOSITORY={{.Repository}}
BINARY={{.Binary}}
WORKFLOW={{.Workflow}}
ASSET_PATTERN={{.AssetPattern}}
CHECKSUM_PATTERN={{.ChecksumPattern}}
VERIFICATION={{.Verification}}
INSTALL_DIR=${INSTALL_DIR:-/usr/local/bin}

fail() {
	printf '%s\n' "insmith: $*" >&2
	exit 1
}

need() {
	command -v "$1" >/dev/null 2>&1 || fail "required command not found: $1"
}

urlencode_tag() {
	# GitHub release tags conventionally require no encoding. Reject unsafe input instead.
	case "$1" in *[!A-Za-z0-9._/-]*) fail "unsupported version: $1" ;; esac
	printf '%s' "$1"
}

version=${1:-}
if [ -z "$version" ]; then
	need curl
	version=$(curl -fsSL "https://api.github.com/repos/$REPOSITORY/releases/latest" |
		sed -n 's/^[[:space:]]*"tag_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -n 1)
	[ -n "$version" ] || fail "could not determine the latest release"
fi
tag=$(urlencode_tag "$version")

case $(uname -s) in
	Linux) os=linux ;;
	Darwin) os=darwin ;;
	*) fail "unsupported operating system: $(uname -s)" ;;
esac
case $(uname -m) in
	x86_64|amd64) arch=amd64 ;;
	aarch64|arm64) arch=arm64 ;;
	*) fail "unsupported architecture: $(uname -m)" ;;
esac

asset_base=$(printf '%s' "$ASSET_PATTERN" |
	sed -e "s/{binary}/$BINARY/g" -e "s/{version}/$version/g" -e "s/{os}/$os/g" -e "s/{arch}/$arch/g")
release_api="https://api.github.com/repos/$REPOSITORY/releases/tags/$tag"
release_json=$(curl -fsSL "$release_api") || fail "could not find release $version"
asset_urls=$(printf '%s\n' "$release_json" |
	sed -n 's/^[[:space:]]*"browser_download_url"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')

matches=
for extension in .tar.gz .zip ''; do
	candidate=$asset_base$extension
	found=$(printf '%s\n' "$asset_urls" | grep "/$candidate$" || true)
	[ -z "$found" ] || matches="${matches}${matches:+
}$found"
done
[ -n "$matches" ] || fail "could not find an asset matching $asset_base (.tar.gz, .zip, or raw binary)"
[ "$(printf '%s\n' "$matches" | wc -l | tr -d ' ')" -eq 1 ] ||
	fail "asset selection is ambiguous for $asset_base"
asset_url=$matches
asset_name=${asset_url##*/}

tmpdir=$(mktemp -d "${TMPDIR:-/tmp}/insmith.XXXXXX") || fail "could not create temporary directory"
trap 'rm -rf "$tmpdir"' EXIT HUP INT TERM
artifact="$tmpdir/$asset_name"
curl -fsSL "$asset_url" -o "$artifact" || fail "could not download $asset_name"

verify_checksum() {
	checksum_name=$(printf '%s' "$CHECKSUM_PATTERN" |
		sed -e "s/{version}/$version/g" -e "s/{binary}/$BINARY/g")
	checksum_url=$(printf '%s\n' "$asset_urls" | grep "/$checksum_name$" || true)
	[ "$(printf '%s\n' "$checksum_url" | sed '/^$/d' | wc -l | tr -d ' ')" -eq 1 ] ||
		fail "could not find a unique checksum asset named $checksum_name"
	checksums="$tmpdir/$checksum_name"
	curl -fsSL "$checksum_url" -o "$checksums" || fail "could not download checksums"
	expected=$(awk -v name="$asset_name" '$2 == name || $2 == "*" name { print $1; exit }' "$checksums")
	[ -n "$expected" ] || fail "checksum for $asset_name is missing"
	if command -v sha256sum >/dev/null 2>&1; then
		actual=$(sha256sum "$artifact" | awk '{print $1}')
	elif command -v shasum >/dev/null 2>&1; then
		actual=$(shasum -a 256 "$artifact" | awk '{print $1}')
	elif command -v openssl >/dev/null 2>&1; then
		actual=$(openssl dgst -sha256 "$artifact" | awk '{print $NF}')
	else
		fail "no SHA-256 command is available"
	fi
	[ "$expected" = "$actual" ] || fail "checksum verification failed for $asset_name"
}

verify_attestation() {
	command -v gh >/dev/null 2>&1 || return 2
	gh attestation verify --help >/dev/null 2>&1 || return 2
	command -v git >/dev/null 2>&1 || return 2
	commit=$(git ls-remote "https://github.com/$REPOSITORY.git" "refs/tags/$tag^{}" | awk 'NR == 1 { print $1 }')
	if [ -z "$commit" ]; then
		commit=$(git ls-remote "https://github.com/$REPOSITORY.git" "refs/tags/$tag" | awk 'NR == 1 { print $1 }')
	fi
	[ -n "$commit" ] || return 2
	if [ -n "$WORKFLOW" ]; then
		gh attestation verify "$artifact" --repo "$REPOSITORY" --source-digest "$commit" --signer-digest "$commit" --signer-workflow "$WORKFLOW"
	else
		gh attestation verify "$artifact" --repo "$REPOSITORY" --source-digest "$commit" --signer-digest "$commit"
	fi
}

case "$VERIFICATION" in
	none) ;;
	checksum) verify_checksum ;;
	attestation)
		verify_attestation || {
			status=$?
			[ "$status" -eq 2 ] && fail "GitHub attestation verification is unavailable"
			fail "attestation verification failed"
		}
		;;
	attestation-or-checksum)
		if verify_attestation; then
			:
		else
			status=$?
			[ "$status" -eq 2 ] && verify_checksum
			[ "$status" -eq 2 ] || fail "attestation verification failed"
		fi
		;;
esac

case "$asset_name" in
	*.tar.gz)
		need tar
		tar -xzf "$artifact" -C "$tmpdir"
		;;
	*.zip)
		need unzip
		unzip -q "$artifact" -d "$tmpdir"
		;;
	*)
		cp "$artifact" "$tmpdir/$BINARY"
		;;
esac
executable=$(find "$tmpdir" -type f -name "$BINARY" -perm -u+x -print | head -n 1)
[ -n "$executable" ] || fail "could not find executable $BINARY in $asset_name"
mkdir -p "$INSTALL_DIR" || fail "could not create $INSTALL_DIR"
install -m 0755 "$executable" "$INSTALL_DIR/$BINARY" || fail "could not install $BINARY"
printf 'Installed %s to %s\n' "$BINARY" "$INSTALL_DIR/$BINARY"
`))
