#!/bin/sh
# Code generated by insmith. DO NOT EDIT.
set -eu

REPOSITORY='Songmu/gitrail'
BINARY='gitrail'
WORKFLOW='Songmu/gitrail/.github/workflows/release-build.yaml'
ASSET_PATTERN='{binary}_{version}_{os}_{arch}'
CHECKSUM_PATTERN='SHA256SUMS'
VERIFICATION='attestation-or-checksum'

fail() {
	printf '%s\n' "insmith: $*" >&2
	exit 1
}

info() {
	printf '%s\n' "$*" >&2
}

usage() {
	status=${1:-2}
	cat >&2 <<EOF
Usage: $0 [-b bindir] [tag]

  -b bindir  installation directory (default: BINDIR or ./bin)
  -h         show this help
EOF
	exit "$status"
}

need() {
	command -v "$1" >/dev/null 2>&1 || fail "required command not found: $1"
}

cleanup() {
	if [ -n "${install_tmp:-}" ]; then
		rm -f "$install_tmp"
		install_tmp=
	fi
	if [ -n "${tmpdir:-}" ]; then
		rm -rf "$tmpdir"
		tmpdir=
	fi
}

parse_args() {
	BINDIR=${BINDIR:-./bin}
	while getopts "b:h" arg; do
		case "$arg" in
			b) BINDIR=$OPTARG ;;
			h) usage 0 ;;
			*) usage 2 ;;
		esac
	done
	shift $((OPTIND - 1))
	[ "$#" -le 1 ] || usage 2
	[ -n "$BINDIR" ] || fail "installation directory must not be empty"
	version=${1:-}
}

validate_tag() {
	case "$1" in
		""|*[!A-Za-z0-9._+-]*) return 1 ;;
	esac
}

asset_url_for_name() {
	wanted=$1
	while IFS= read -r url; do
		[ "${url##*/}" = "$wanted" ] && printf '%s\n' "$url"
	done <<-EOF
	$asset_urls
	EOF
	return 0
}

line_count() {
	sed '/^$/d' | wc -l | tr -d ' '
}

sha256() {
	if command -v gsha256sum >/dev/null 2>&1; then
		gsha256sum "$1" | awk '{print $1}'
	elif command -v sha256sum >/dev/null 2>&1; then
		sha256sum "$1" | awk '{print $1}'
	elif command -v shasum >/dev/null 2>&1; then
		shasum -a 256 "$1" | awk '{print $1}'
	elif command -v openssl >/dev/null 2>&1; then
		openssl dgst -sha256 "$1" | awk '{print $NF}'
	else
		return 1
	fi
}

verify_checksum() {
	checksum_name=$(printf '%s' "$CHECKSUM_PATTERN" |
		sed -e "s/{version}/$tag/g" -e "s/{binary}/$BINARY/g" -e "s/{os}/$os/g" -e "s/{arch}/$arch/g")
	checksum_urls=$(asset_url_for_name "$checksum_name")
	[ "$(printf '%s\n' "$checksum_urls" | line_count)" -eq 1 ] ||
		fail "could not find a unique checksum asset named $checksum_name"
	checksum_url=$checksum_urls
	checksums="$tmpdir/$checksum_name"
	curl --proto '=https' --proto-redir '=https' --tlsv1.2 -fsSL "$checksum_url" -o "$checksums" ||
		fail "could not download checksums"
	expected=$(awk -v name="$asset_name" '
		{
			file = $2
			sub(/^\*/, "", file)
			sub(/^.*\//, "", file)
			if (file == name) print $1
		}
	' "$checksums")
	[ "$(printf '%s\n' "$expected" | line_count)" -eq 1 ] ||
		fail "checksum for $asset_name must appear exactly once"
	[ "${#expected}" -eq 64 ] || fail "checksum for $asset_name is not SHA-256"
	case "$expected" in
		*[!0-9A-Fa-f]*) fail "checksum for $asset_name is not SHA-256" ;;
	esac
	actual=$(sha256 "$artifact") || fail "no SHA-256 command is available"
	expected=$(printf '%s' "$expected" | tr 'A-F' 'a-f')
	actual=$(printf '%s' "$actual" | tr 'A-F' 'a-f')
	[ "$expected" = "$actual" ] || fail "checksum verification failed for $asset_name"
	info "Verified SHA-256 checksum for $asset_name"
}

attestation_capability() {
	command -v gh >/dev/null 2>&1 || return 2
	command -v git >/dev/null 2>&1 || return 2
	command -v grep >/dev/null 2>&1 || return 2
	# gh <= 2.92.0 may expose credentials to untrusted TUF mirrors during
	# attestation verification (GHSA-8xvp-7hj6-mcj9).
	gh --version 2>/dev/null | awk '
		NR == 1 {
			if ($3 !~ /^[0-9]+\.[0-9]+\.[0-9]+$/) exit 1
			split($3, version, ".")
			exit !(version[1] > 2 || (version[1] == 2 && version[2] >= 93))
		}
		END { if (NR == 0) exit 1 }
	' || return 2
	gh attestation verify --help 2>/dev/null | grep -q -- '--signer-digest' || return 2
}

resolve_tag_commit() {
	refs=$(git ls-remote "https://github.com/$REPOSITORY.git" \
		"refs/tags/$tag" "refs/tags/$tag^{}") || return 1
	printf '%s\n' "$refs" | awk '
		$2 ~ /\^\{\}$/ { peeled = $1 }
		$2 !~ /\^\{\}$/ { direct = $1 }
		END {
			if (peeled != "") print peeled
			else if (direct != "") print direct
		}
	'
}

verify_attestation() {
	attestation_capability || return 2
	commit=$(resolve_tag_commit) || return 3
	[ -n "$commit" ] || return 3
	info "Verifying build provenance for $asset_name"
	if [ -n "$WORKFLOW" ]; then
		gh attestation verify "$artifact" \
			--repo "$REPOSITORY" \
			--source-digest "$commit" \
			--signer-digest "$commit" \
			--signer-workflow "$WORKFLOW" || return 1
	else
		gh attestation verify "$artifact" \
			--repo "$REPOSITORY" \
			--source-digest "$commit" \
			--signer-digest "$commit" || return 1
	fi
}

verify_artifact() {
	case "$VERIFICATION" in
		none) ;;
		checksum) verify_checksum ;;
		attestation)
			if verify_attestation; then
				:
			else
				status=$?
				case "$status" in
					2) fail "GitHub attestation verification is unavailable" ;;
					3) fail "could not resolve release tag $tag to a commit" ;;
					*) fail "attestation verification failed" ;;
				esac
			fi
			;;
		attestation-or-checksum)
			if verify_attestation; then
				:
			else
				status=$?
				case "$status" in
					2)
						info "Build provenance verification unavailable; falling back to SHA-256"
						verify_checksum
						;;
					3) fail "could not resolve release tag $tag to a commit" ;;
					*) fail "attestation verification failed" ;;
				esac
			fi
			;;
	esac
}

check_archive_member() {
	member=$1
	case "$member" in
		/*) fail "archive contains an absolute path: $member" ;;
	esac
	case "/$member/" in
		*/../*) fail "archive contains a path traversal entry: $member" ;;
	esac
}

check_tar_types() {
	while IFS= read -r line; do
		case "$line" in
			-*|d*) ;;
			l*) fail "archive contains a symlink entry which is not supported" ;;
			h*) fail "archive contains a hard link entry which is not supported" ;;
			*) fail "archive contains an unsupported entry type" ;;
		esac
	done <<-EOF
	$1
	EOF
}

check_zip_types() {
	listing=$1
	expected=$2
	checked=0
	while IFS= read -r line; do
		case "$line" in
			-?????????*|d?????????*) checked=$((checked + 1)) ;;
			l?????????*) fail "archive contains a symlink entry which is not supported" ;;
			h?????????*) fail "archive contains a hard link entry which is not supported" ;;
			b?????????*|c?????????*|p?????????*|s?????????*)
				fail "archive contains an unsupported entry type"
				;;
		esac
	done <<-EOF
	$listing
	EOF
	[ "$checked" -eq "$expected" ] || fail "could not validate all zip entry types"
}

extract_artifact() {
	executable=
	extractdir="$tmpdir/extract"
	mkdir -p "$extractdir" || fail "could not create extraction directory"
	case "$asset_name" in
		*.tar.gz)
			need tar
			tar_listing=$(tar -tvzf "$artifact") || fail "could not list $asset_name contents"
			check_tar_types "$tar_listing"
			tar_names=$(tar -tzf "$artifact") || fail "could not list $asset_name contents"
			while IFS= read -r member; do
				[ -n "$member" ] || continue
				check_archive_member "$member"
			done <<-EOF
			$tar_names
			EOF
			tar -xzf "$artifact" -C "$extractdir" || fail "could not extract $asset_name"
			;;
		*.zip)
			need unzip
			zip_names=$(unzip -Z1 "$artifact") || fail "could not list $asset_name contents"
			while IFS= read -r member; do
				[ -n "$member" ] || continue
				check_archive_member "$member"
			done <<-EOF
			$zip_names
			EOF
			zip_types=$(unzip -Z -s "$artifact") || fail "could not list $asset_name contents"
			zip_count=$(printf '%s\n' "$zip_names" | line_count)
			check_zip_types "$zip_types" "$zip_count"
			unzip -q "$artifact" -d "$extractdir" || fail "could not extract $asset_name"
			;;
		*)
			executable=$artifact
			;;
	esac
	if [ -z "$executable" ]; then
		executables=$(find "$extractdir" -type f -name "$BINARY" -print)
		[ "$(printf '%s\n' "$executables" | line_count)" -eq 1 ] ||
			fail "archive must contain exactly one executable named $BINARY"
		executable=$executables
	fi
}

install_artifact() {
	need install
	need mv
	install -d "$BINDIR" || fail "could not create $BINDIR"
	install_tmp=$(mktemp "${BINDIR%/}/.${BINARY}.XXXXXX") ||
		fail "could not create temporary file in $BINDIR"
	install -m 0755 "$executable" "$install_tmp" || fail "could not prepare $BINARY"
	mv -f "$install_tmp" "$BINDIR/$BINARY" || fail "could not install $BINARY"
	install_tmp=
	printf 'Installed %s to %s\n' "$BINARY" "$BINDIR/$BINARY"
}

main() {
	parse_args "$@"
	for command in curl uname sed awk wc tr mktemp find rm mkdir; do
		need "$command"
	done

	if [ -z "$version" ]; then
		version=$(curl --proto '=https' --proto-redir '=https' --tlsv1.2 -fsSL \
			"https://api.github.com/repos/$REPOSITORY/releases/latest" |
			sed -n 's/^[[:space:]]*"tag_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')
		[ "$(printf '%s\n' "$version" | line_count)" -eq 1 ] ||
			fail "could not determine a unique latest release"
	fi
	validate_tag "$version" || fail "unsupported version: $version"
	tag=$version

	case $(uname -s) in
		Linux) os=linux ;;
		Darwin) os=darwin ;;
		*) fail "unsupported operating system: $(uname -s)" ;;
	esac
	case $(uname -m) in
		x86_64|amd64) arch=amd64 ;;
		aarch64|arm64) arch=arm64 ;;
		*) fail "unsupported architecture: $(uname -m)" ;;
	esac

	asset_base=$(printf '%s' "$ASSET_PATTERN" |
		sed -e "s/{binary}/$BINARY/g" -e "s/{version}/$tag/g" -e "s/{os}/$os/g" -e "s/{arch}/$arch/g")
	release_api="https://api.github.com/repos/$REPOSITORY/releases/tags/$tag"
	release_json=$(curl --proto '=https' --proto-redir '=https' --tlsv1.2 -fsSL "$release_api") ||
		fail "could not find release $version"
	asset_urls=$(printf '%s\n' "$release_json" |
		sed -n 's/^[[:space:]]*"browser_download_url"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')

	matches=
	for extension in .tar.gz .zip ''; do
		candidate=$asset_base$extension
		found=$(asset_url_for_name "$candidate")
		[ -z "$found" ] || matches="${matches}${matches:+
}$found"
	done
	[ "$(printf '%s\n' "$matches" | line_count)" -eq 1 ] ||
		fail "could not find a unique asset matching $asset_base (.tar.gz, .zip, or raw binary)"
	asset_url=$matches
	asset_name=${asset_url##*/}

	tmpdir=$(mktemp -d "${TMPDIR:-/tmp}/insmith.XXXXXX") ||
		fail "could not create temporary directory"
	install_tmp=
	trap cleanup 0
	trap 'exit 1' HUP INT TERM

	artifact="$tmpdir/$asset_name"
	curl --proto '=https' --proto-redir '=https' --tlsv1.2 -fsSL "$asset_url" -o "$artifact" ||
		fail "could not download $asset_name"
	verify_artifact
	extract_artifact
	install_artifact

	cleanup
	trap - 0 HUP INT TERM
}

main "$@"
